name: kflow-ci
run-name: "CI - ${{ github.ref_name }} (${{ github.event_name }})"

# Run CI on pushes/PRs to master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# Only keep the latest run per branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Read-only permissions
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Fetch repo content
      - uses: actions/checkout@v4

      # Install Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Install Python and enable pip caching
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: pyproject.toml

      # Install project package and testing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-mock

      # Run the unit tests
      - name: Run unit tests
        run: pytest -v tests
